# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 03:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20170412_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 16, 3, 31, 31, 106874), verbose_name='date joined'),
        ),
    ]
