# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_auto_20170416_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 19, 23, 21, 616722), verbose_name='date joined'),
        ),
    ]
