# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_auto_20170517_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 19, 34, 18, 907849), verbose_name='date joined'),
        ),
    ]
